dist: trusty
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
env:
  -
  - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
before_script:
  - truffle version
script:
  - npm run lint
  - npm run lint:sol
  - npm run test
